/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLandingImport } from './routes/_auth.landing'
import { Route as AuthForm29Import } from './routes/_auth.form-29'

// Create Virtual Routes

const AuthAccountsLazyImport = createFileRoute('/_auth/accounts')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAccountsLazyRoute = AuthAccountsLazyImport.update({
  path: '/accounts',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth.accounts.lazy').then((d) => d.Route),
)

const AuthLandingRoute = AuthLandingImport.update({
  path: '/landing',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForm29Route = AuthForm29Import.update({
  path: '/form-29',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/form-29': {
      preLoaderRoute: typeof AuthForm29Import
      parentRoute: typeof AuthImport
    }
    '/_auth/landing': {
      preLoaderRoute: typeof AuthLandingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/accounts': {
      preLoaderRoute: typeof AuthAccountsLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthForm29Route,
    AuthLandingRoute,
    AuthAccountsLazyRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
