/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthorizedImport } from './routes/_authorized'
import { Route as IndexImport } from './routes/index'
import { Route as AuthorizedLandingImport } from './routes/_authorized/landing'
import { Route as AuthorizedForm29Import } from './routes/_authorized/form-29'
import { Route as AuthorizedAccountsImport } from './routes/_authorized/accounts'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthorizedRoute = AuthorizedImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorizedLandingRoute = AuthorizedLandingImport.update({
  path: '/landing',
  getParentRoute: () => AuthorizedRoute,
} as any)

const AuthorizedForm29Route = AuthorizedForm29Import.update({
  path: '/form-29',
  getParentRoute: () => AuthorizedRoute,
} as any)

const AuthorizedAccountsRoute = AuthorizedAccountsImport.update({
  path: '/accounts',
  getParentRoute: () => AuthorizedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authorized': {
      preLoaderRoute: typeof AuthorizedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authorized/accounts': {
      preLoaderRoute: typeof AuthorizedAccountsImport
      parentRoute: typeof AuthorizedImport
    }
    '/_authorized/form-29': {
      preLoaderRoute: typeof AuthorizedForm29Import
      parentRoute: typeof AuthorizedImport
    }
    '/_authorized/landing': {
      preLoaderRoute: typeof AuthorizedLandingImport
      parentRoute: typeof AuthorizedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthorizedRoute.addChildren([
    AuthorizedAccountsRoute,
    AuthorizedForm29Route,
    AuthorizedLandingRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
